#!/bin/bash
set -eo pipefail

BASE_DIR="${BASE_DIR:-/mnt/efs}"
DEFAULT_JNOTE_HOME="$BASE_DIR/${JNOTE_COURSE_CODE,,}"
DEFAULT_JNOTE_SNAP="$BASE_DIR/${JNOTE_COURSE_CODE,,}-snap"
DEFAULT_JNOTE_INTSNAP="$BASE_DIR/${JNOTE_COURSE_CODE,,}-internal"

export JNOTE_HOME="${JNOTE_HOME:-$DEFAULT_JNOTE_HOME}"
export JNOTE_SNAP="${JNOTE_SNAP:-$DEFAULT_JNOTE_SNAP}"
export JNOTE_INTSNAP="${JNOTE_INTSNAP:-$DEFAULT_JNOTE_INTSNAP}"

DEFAULT_MODULE_NAME=wsgi
MODULE_NAME=${MODULE_NAME:-$DEFAULT_MODULE_NAME}
VARIABLE_NAME=${VARIABLE_NAME:-application}
export APP_MODULE=${APP_MODULE:-"$MODULE_NAME:$VARIABLE_NAME"}

exec "$@"
